### ISSUE TITLE
RuntimeError 

### ISSUE THREAD

**Issue by abviv** [nate-gillman/fourier-head#10]
![image](https://github.com/user-attachments/assets/1cea8308-c3fc-4147-ae79-69275c813ff5)

Hey! Seems like while running the fourier_head.py as a standalone would lead to type casting issue of how torch.complex handles dtypes.

torch.__version__ = 2.4.1

**Comment by nate-gillman** [comment]
Thanks for reporting this! I've tested+merged in your fix (PR [https://github.com/nate-gillman/fourier-head/pull/11](https://github.com/nate-gillman/fourier-head/pull/11)).

Cheers
Nate
